module.exports = {
  tour: [{
    date: 'Nov 17, 2019',
    datetime: new Date('November 17, 2019'),
    time: '1:00 pm',
    location: 'Salem, VA',
    venue: '<a href="https://parkwaybrewing.com/" rel="noopener noreferrer" target="_blank">Parkway Brewing Co.</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Oct 4, 2019',
    datetime: new Date('October 4, 2019'),
    time: '6:00 pm',
    location: 'Roanoke, VA',
    venue: '<a href="http://valhallawines.com/" rel="noopener noreferrer" target="_blank">Valhalla Winery</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Sep 28, 2019',
    datetime: new Date('September 28, 2019'),
    time: '5:30 pm',
    location: 'Marion, VA', // eslint-disable-next-line max-len
    venue: '<a target="_blank" rel="noopener noreferrer" href="http://hungrymother.org/contact-us/">Hungry Mother Lutheran Retreat Center</a> - Beer & Brats Fundraiser',
    tickets: 'Donation',
    more: '',
  },
  {
    date: 'Sep 15, 2019',
    datetime: new Date('September 15, 2019'),
    time: '5:00 pm',
    location: 'Salem, VA',
    venue: '<a href="https://collegelutheran.org/" rel="noopener noreferrer" target="_blank">College Lutheran Church</a> - Folk Service',
    tickets: 'Freewill',
    more: '',
  },
  {
    date: 'Sep 14, 2019',
    datetime: new Date('September 14, 2019'),
    time: '9:00 am',
    location: 'Salem, VA', // eslint-disable-next-line max-len
    venue: 'Front porch at <a href="https://collegelutheran.org/" rel="noopener noreferrer" target="_blank">College Lutheran Church</a>, during <a href="http://www.oldesalemdays.com/" rel="noopener noreferrer" target="_blank">Olde Salem Days</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Sep 7, 2019',
    datetime: new Date('September 7, 2019'),
    time: '1:00 pm',
    location: 'Floyd, VA',
    venue: '<a href="https://villaappalaccia.com/" rel="noopener noreferrer" target="_blank">Villa Appalaccia Winery</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Aug 31, 2019',
    datetime: new Date('August 31, 2019'),
    time: '4:00 pm',
    location: 'Bent Mountain, VA',
    venue: '34th Annual Pig Roast',
    tickets: 'Sold out',
    more: '',
  },
  {
    date: 'Jun 21, 2019',
    datetime: new Date('June 21, 2019'),
    time: '6:00 pm',
    location: 'Roanoke, VA',
    venue: '<a href="http://valhallawines.com/" rel="noopener noreferrer" target="_blank">Valhalla Winery</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Dec 24, 2018',
    datetime: new Date('December 24, 2018'),
    time: '4:30 pm',
    location: 'Salem, VA',
    venue: '<a href="http://collegelutheran.org/" rel="noopener noreferrer" target="_blank">College Lutheran Church</a>',
    tickets: 'Freewill',
    more: '',
  },
  {
    date: 'Dec 16, 2018',
    datetime: new Date('December 16, 2018'),
    time: '6:00 pm',
    location: 'Martinsville, VA',
    venue: '<a href="https://stjoechurch.net/" rel="noopener noreferrer" target="_blank">St. Joseph Catholic Church</a>, Christmas party',
    tickets: 'Private',
    more: '',
  },
  {
    date: 'Dec 7, 2018',
    datetime: new Date('December 7, 2018'),
    time: '6:00 pm',
    location: 'Salem, VA', // eslint-disable-next-line max-len
    venue: '<a href="http://collegelutheran.org/" rel="noopener noreferrer" target="_blank">College Lutheran Church</a> front porch, prior to the Salem Christmas parade',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Nov 29, 2018',
    datetime: new Date('November 29, 2018'),
    time: '5:45 pm',
    location: 'Salem, VA',
    venue: 'Dinner to Honor Volunteers/Supporters of the Salem Clothes Closet',
    tickets: 'Private',
    more: '',
  },
  {
    date: 'Nov 24, 2018',
    datetime: new Date('November 24, 2018'),
    time: '4:45 pm',
    location: 'Moneta, VA',
    venue: '<a href="http://www.resurrectioncatholic.org/" rel="noopener noreferrer" target="_blank">Resurrection Catholic Church</a>',
    tickets: 'Freewill',
    more: '',
  },
  {
    date: 'Sep 29, 2018',
    datetime: new Date('September 29, 2018'),
    time: '5:30 pm',
    location: 'Marion, VA', // eslint-disable-next-line max-len
    venue: 'Hungry Mother Lutheran Retreat Center Beer & Brats Fundraiser - <a target="_blank" rel="noopener noreferrer" href="http://hungrymother.org/contact-us/">Contact</a> for more info.',
    tickets: 'Donation',
    more: '',
  },
  {
    date: 'Sep 1, 2018',
    datetime: new Date('September 1, 2018'),
    time: '4:00 pm',
    location: 'Bent Mountain, VA',
    venue: '33rd Annual Pig Roast',
    tickets: 'Sold out',
    more: '',
  },
  {
    date: 'Aug 4, 2018',
    datetime: new Date('August 4, 2018'),
    time: '9:00 am',
    location: 'Salem, VA',
    venue: '<a href="https://www.facebook.com/SalemVaMarket/" rel="noopener noreferrer" target="_blank">Farmers Market</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Jul 30, 2018',
    datetime: new Date('July 30, 2018'),
    time: '6:00 pm',
    location: 'Salem, VA', // eslint-disable-next-line max-len
    venue: '<a href="https://www.facebook.com/pages/biz/Majestic-Mic-at-Parkway-Brewery-1146829528673810/" rel="noopener noreferrer" target="_blank">Parkway Brewery</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Jul 21, 2018',
    datetime: new Date('July 21, 2018'),
    time: '5:00 pm',
    location: 'Salem, VA',
    venue: '<a href="https://www.facebook.com/events/199874127371694/" rel="noopener noreferrer" target="_blank">Web Jam LLC</a>',
    tickets: 'Private',
    more: '',
  },
  {
    date: 'Jul 15, 2018',
    datetime: new Date('July 15, 2018'),
    time: '9:45 am',
    location: 'Salem, VA',
    venue: '<a href="http://collegelutheran.org" rel="noopener noreferrer" target="_blank">College Lutheran Church</a>',
    tickets: 'Freewill',
    more: '',
  },
  ],
};
