const makefuture = (day:number) => {
  const today = new Date();
  const future = new Date(today);
  future.setDate(future.getDate() + day);
  return future;
};
export default {
  tour: [{
    date: 'Nov 17, 2019',
    datetime: new Date('November 17, 2019'),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: '<a href="https://parkwaybrewing.com/" rel="noopener noreferrer" target="_blank">Parkway Brewing Co.</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'future 1',
    datetime: makefuture(1),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: 'future 1',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'future 2',
    datetime: makefuture(2),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: 'future 2',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'future 3',
    datetime: makefuture(3),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: 'future 3',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'future 4',
    datetime: makefuture(4),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: 'future 4',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'future 5',
    datetime: makefuture(5),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: 'future 5',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'future 6',
    datetime: makefuture(6),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: 'future 6',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'future 7',
    datetime: makefuture(7),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: 'future 7',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'future 8',
    datetime: makefuture(8),
    time: '1:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: 'future 8',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Oct 4, 2019',
    datetime: new Date('October 4, 2019'),
    time: '6:00 pm',
    city: 'Roanoke',
    usState: 'Virginia',
    venue: '<a href="http://valhallawines.com/" rel="noopener noreferrer" target="_blank">Valhalla Winery</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Sep 28, 2019',
    datetime: new Date('September 28, 2019'),
    time: '5:30 pm',
    city: 'Marion',
    usState: 'Virginia', // eslint-disable-next-line max-len
    venue: '<a target="_blank" rel="noopener noreferrer" href="http://hungrymother.org/contact-us/">Hungry Mother Lutheran Retreat Center</a> - Beer & Brats Fundraiser',
    tickets: 'Donation',
    more: '',
  },
  {
    date: 'Sep 15, 2019',
    datetime: new Date('September 15, 2019'),
    time: '5:00 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: '<a href="https://collegelutheran.org/" rel="noopener noreferrer" target="_blank">College Lutheran Church</a> - Folk Service',
    tickets: 'Freewill',
    more: '',
  },
  {
    date: 'Sep 14, 2019',
    datetime: new Date('September 14, 2019'),
    time: '9:00 am',
    city: 'Salem',
    usState: 'Virginia',
    // eslint-disable-next-line max-len
    venue: 'Front porch at <a href="https://collegelutheran.org/" rel="noopener noreferrer" target="_blank">College Lutheran Church</a>, during <a href="http://www.oldesalemdays.com/" rel="noopener noreferrer" target="_blank">Olde Salem Days</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Sep 7, 2019',
    datetime: new Date('September 7, 2019'),
    time: '1:00 pm',
    city: 'Floyd',
    usState: 'Virginia',
    venue: '<a href="https://villaappalaccia.com/" rel="noopener noreferrer" target="_blank">Villa Appalaccia Winery</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Aug 31, 2019',
    datetime: new Date('August 31, 2019'),
    time: '4:00 pm',
    city: 'Bent Mountain',
    usState: 'Virginia',
    venue: '34th Annual Pig Roast',
    tickets: 'Sold out',
    more: '',
  },
  {
    date: 'Jun 21, 2019',
    datetime: new Date('June 21, 2019'),
    time: '6:00 pm',
    city: 'Roanoke',
    usState: 'Virginia',
    venue: '<a href="http://valhallawines.com/" rel="noopener noreferrer" target="_blank">Valhalla Winery</a>',
    tickets: 'Free',
    more: '',
  },
  {
    date: 'Dec 24, 2018',
    datetime: new Date('December 24, 2018'),
    time: '4:30 pm',
    city: 'Salem',
    usState: 'Virginia',
    venue: '<a href="http://collegelutheran.org/" rel="noopener noreferrer" target="_blank">College Lutheran Church</a>',
    tickets: 'Freewill',
    more: '',
  },
  {
    date: 'Dec 16, 2018',
    datetime: new Date('December 16, 2018'),
    time: '6:00 pm',
    city: 'Martinsville',
    usState: 'Virginia',
    venue: '<a href="https://stjoechurch.net/" rel="noopener noreferrer" target="_blank">St. Joseph Catholic Church</a>, Christmas party',
    tickets: 'Private',
    more: '',
  },
  ],
};
